// Native demo weather controller. External resource data retains its own license.
#define NOMINMAX
#include "stdafx.h"
#include "MirvWeather.h"
#include "MirvWeatherStorm.h"
#include "MirvTime.h"
#include "Globals.h"
#include "SceneSystem.h"
#include "DeathMsg.h"
#include "SchemaSystem.h"
#include "ClientEntitySystem.h"
#include "MirvPovCore.h"
#include "hlaeFolder.h"
#include "../deps/release/prop/cs2/sdk_src/public/cdll_int.h"
#include <atomic>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <shared_mutex>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>

extern SOURCESDK::CS2::ISource2EngineToClient * g_pEngineToClient;
extern bool getOffset(ptrdiff_t *, std::string, std::string, std::string);

namespace {
struct Vec3 { float x, y, z; };
using ManagerFn = void * (__fastcall *)();
using CreateFn = int * (__fastcall *)(void *, int *, const char *, int, int64_t, int64_t, int64_t, int64_t);
using UpdateFn = void (__fastcall *)(void *, int, int, const Vec3 *, float);
using DestroyFn = void (__fastcall *)(void *, int, bool, bool);
ManagerFn managerFn = nullptr;
CreateFn createFn = nullptr;
UpdateFn updateFn = nullptr;
DestroyFn destroyFn = nullptr;
ptrdiff_t postSettingsOffset = -1;
using WorldFn = void * (__fastcall *)(void *, uint32_t);
using RainContactFn = void (__fastcall *)(void *, void *, bool);
WorldFn worldFn = nullptr;
void ** contactSceneAddress = nullptr, ** contactWorldAddress = nullptr;
ptrdiff_t identityOffset = -1, worldGroupOffset = -1, rainContactOffset = -1;
bool contactSchemaReady = false, contactWarning = false, postSchemaWarning = false;
struct ContactState {
    SOURCESDK::CS2::CBaseHandle handle;
    uint32_t worldGroup;
    void * scene;
    void * world;
    bool original;
};
std::vector<ContactState> contactStates;
using RainEnvironmentFn = void (__fastcall *)(void *, void *, float, float, float, float, float);
struct EnvironmentState {
    SOURCESDK::CS2::CBaseHandle handle;
    uint32_t worldGroup;
    void * scene;
    void * world;
    std::array<float, 5> original;
};
std::vector<EnvironmentState> environmentStates;
std::array<ptrdiff_t, 5> environmentOffsets {{ -1, -1, -1, -1, -1 }};
std::array<float, 5> weatherEnvironment {{ 1, 1, 0, 1, 0 }};
bool environmentSignatureReady = false, environmentSchemaReady = false, environmentWarning = false;
struct MapProfile { const char * map; const char * file; size_t rainCount; size_t materialCount; };
const MapProfile mapProfiles[] = {
    { "de_dust2", "dust2.txt", 385, 18 },
    { "de_mirage", "mirage.txt", 832, 12 },
    { "de_cache", "cache.txt", 969, 3 },
    { "de_inferno", "inferno.txt", 604, 2 },
    { "de_ancient", "ancient.txt", 166, 0 },
    { "de_nuke", "nuke.txt", 221, 0 },
    { "de_anubis", "anubis.txt", 1004, 0 }
};
const MapProfile * loadedProfile = nullptr;
void ** mapInfoVtable = nullptr, ** postVolumeVtable = nullptr;
std::vector<SOURCESDK::CS2::CBaseHandle> mapInfoHandles, postVolumeHandles;
ULONGLONG lastEntityScan = 0;
bool requested = false, wantRain = true, wantGround = true, wantPost = true, wantContact = true;
bool configLoaded = false, loadAttempted = false, rainAttempted = false;
bool groundReady = false, postReady = false;
bool groundLoadAttempted = false, postLoadAttempted = false;
std::atomic<bool> groundActive { false };
std::shared_mutex materialMutex;
std::unordered_map<std::string, CMaterial2 *> wetMaterials;
std::vector<CMaterial2 **> retainedWetBindings;
bool resourcePinLayoutReady = false;
bool postLifetimeLayoutReady = false;
std::vector<Vec3> positions;
struct MaterialEntry { std::string original, wet; };
std::vector<MaterialEntry> materialEntries;
struct Particle { int index; void * record; };
std::vector<Particle> rainParticles;
struct TransientParticle { Particle particle; void * manager; void ** binding; double end; int resource; };
std::vector<TransientParticle> transientParticles;
std::vector<void **> audioBindings;
bool lightningWarning = false, audioPrecacheFailed = false;
// Diagnostic submission counters for the owned native particle paths. They
// record how far each spawn attempt got, not whether anything became visible.
//
// Index 0 is the authored bolt generated by tools/generate_weather_bolt.py and
// installed as resources/AfxHookSource2/cs2/particles/mirv_weather/storm_bolt.vpcf_c.
// The installed game storm_lightning_01_thin/branch rope renderers have
// m_bDisableOperator=true and cannot be claimed as a visible bolt. Index 1 is
// the native cloud, kept only as an optional secondary flash.
constexpr unsigned kLightningResources = 2;
const char * lightningNames[kLightningResources] = {
    "particles/mirv_weather/storm_bolt.vpcf",
    "particles/rain_fx/storm_lightning_01_cloud.vpcf"
};
// The authored bolt lives ~0.22 s; keep the owned transient slightly longer so
// the fade-out completes before the record is destroyed. The native cloud is
// kept for its own native lifetime.
const double lightningLifetime[kLightningResources] = { 0.45, 0.80 };
struct ParticleCounters {
    std::atomic<unsigned> tries {0};
    std::atomic<unsigned> definitionFails {0};
    std::atomic<unsigned> createFails {0};
    std::atomic<unsigned> created {0};
    std::atomic<unsigned> live {0};
    std::atomic<int> stage {MirvWeatherParticleStage_None};
};
ParticleCounters lightningRes[kLightningResources];
ParticleCounters rainCounters;
std::atomic<unsigned> lightningTries {0};
std::atomic<int> lightningStage {MirvWeatherParticleStage_None};
// Manual visible-rope control probe. It references the installed native
// particles/impact_fx/impact_wallbang_light_silent.vpcf control effect by name
// (behavior 12, CreateSequentialPathV2 CP0->CP1, native 1000-unit draw
// distance) purely to confirm that a rope line can be drawn at all. It is not
// the authored bolt and it shares no counters with it.
const char * probeName = "particles/impact_fx/impact_wallbang_light_silent.vpcf";
constexpr unsigned kProbePulses = 3;
constexpr double kProbeDelay = 1.5, kProbeSpacing = 0.75, kProbeLifetime = 1.5;
constexpr size_t kProbeMaxLive = 4;
// Placement stays inside the control particle's native 1000-unit draw
// distance: at most 600 units ahead and 380 units above the camera, with CP1
// 250..300 units above CP0.
struct ProbePulse { float forward, height, length; };
const ProbePulse probePulseTable[kProbePulses] = {
    { 450.0f, 40.0f, 250.0f },
    { 525.0f, 60.0f, 275.0f },
    { 600.0f, 80.0f, 300.0f }
};
struct ProbeParticle { Particle particle; void * manager; void ** binding; double end; };
std::vector<ProbeParticle> probeParticles;
bool probePending = false;
double probeFireAt = -1;
int probeRemaining = 0;
std::atomic<unsigned> probeQueued {0}, probeDropped {0}, probeFired {0}, probeDefinitionFails {0}, probeCreateFails {0}, probeCreated {0}, probeLive {0};
std::atomic<int> probeStage {MirvWeatherParticleStage_None};
void * rainManager = nullptr;
void ** rainResource = nullptr;
struct PostBackup { SOURCESDK::CS2::CBaseHandle handle; void ** original; };
std::vector<PostBackup> postBackups;
void ** postResource = nullptr;
int previousTick = -1;
const char * rainName = "particles/mirv_weather/dust2_rain.vpcf";

// C_PostProcessingVolume's destructor releases its m_hPostSettings binding at
// +0x20. A raw pointer swap must therefore transfer the field's owned reference.
void RetainBinding(void ** binding) {
    if(binding) InterlockedIncrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(binding) + 0x20));
}

void ReleaseBinding(void ** binding) {
    if(binding) InterlockedDecrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(binding) + 0x20));
}

void ReplacePostBinding(void *** field, void ** replacement) {
    if(*field == replacement) return;
    RetainBinding(replacement);
    void ** previous = *field;
    *field = replacement;
    ReleaseBinding(previous);
}

std::string Normalize(std::string s) {
    for(char & c : s) { if(c == '\\') c = '/'; else if(c >= 'A' && c <= 'Z') c += 'a' - 'A'; }
    if(s.size() > 2 && s.compare(s.size()-2, 2, "_c") == 0) s.resize(s.size()-2);
    return s;
}

const MapProfile * GetDemoProfile() {
    if(!g_pEngineToClient) return nullptr;
    auto * demo = g_pEngineToClient->GetDemoFile();
    if(!demo || !demo->IsPlayingDemo()) return nullptr;
    const char * level = g_pEngineToClient->GetLevelNameShort();
    if(level) {
        const std::string name = Normalize(level);
        for(const auto & profile : mapProfiles) if(name == profile.map) return &profile;
    }
    return nullptr;
}

// The matched destroy routine verifies these manager/record fields itself.
// Remember the record as well as its index so a seek cannot destroy a different
// particle when the manager has already discarded our original effect.
void * FindRecord(void * manager, int index) {
    if(!manager || index < 0) return nullptr;
    auto * bytes = static_cast<unsigned char *>(manager);
    int count = *reinterpret_cast<int *>(bytes + 0x98);
    auto ** records = *reinterpret_cast<void ***>(bytes + 0xA0);
    if(count < 0 || count > 32768 || !records) return nullptr;
    for(int i = 0; i < count; ++i) {
        auto * record = static_cast<unsigned char *>(records[i]);
        if(record && *reinterpret_cast<int *>(record + 0x38) == index) return record;
    }
    return nullptr;
}

void StopRain() {
    void * current = managerFn ? managerFn() : nullptr;
    if(destroyFn && current && current == rainManager) {
        for(const auto & p : rainParticles)
            if(p.record && FindRecord(current, p.index) == p.record) destroyFn(current, p.index, true, true);
    }
    rainParticles.clear();
    rainCounters.live.store(0);
    rainManager = nullptr;
    rainAttempted = false;
    ReleaseBinding(rainResource);
    rainResource = nullptr;
}

void RestorePost() {
    if(postSettingsOffset > 0 && g_pEntityList && *g_pEntityList && g_GetEntityFromIndex) {
        for(const auto & b : postBackups) {
            auto * entity = GetEntityFromIndex(b.handle.GetEntryIndex());
            if(!entity || entity->GetHandle() != b.handle) continue;
            auto *** field = reinterpret_cast<void ***>(reinterpret_cast<unsigned char *>(entity) + postSettingsOffset);
            if(*field == postResource) ReplacePostBinding(field, b.original);
        }
    }
    for(const auto & b : postBackups) ReleaseBinding(b.original);
    postBackups.clear();
}

void ClearLightning(bool all) {
    double time=0; g_MirvTime.GetCurrentDemoTime(time);
    void * current=managerFn?managerFn():nullptr;
    for(auto it=transientParticles.begin();it!=transientParticles.end();) {
        if(all || time>=it->end || !MirvPovDebug_IsFeatureEnabled("weather_lightning") || current!=it->manager) {
            if(destroyFn && current==it->manager && FindRecord(current,it->particle.index)==it->particle.record)
                destroyFn(current,it->particle.index,true,true);
            ReleaseBinding(it->binding);
            const int resource=it->resource;
            if(resource>=0 && resource<static_cast<int>(kLightningResources)) {
                std::atomic<unsigned> & live=lightningRes[resource].live;
                unsigned value=live.load();
                if(value) live.store(value-1);
            }
            it=transientParticles.erase(it);
        } else ++it;
    }
}

// Destroy every owned probe control particle and release its definition
// binding. The manager/record identity check keeps a seek from destroying a
// different particle that has already reused our index.
void DestroyProbeOwned() {
    if(probeParticles.empty()) return;
    void * current = managerFn ? managerFn() : nullptr;
    for(const auto & p : probeParticles) {
        if(destroyFn && current == p.manager && FindRecord(current, p.particle.index) == p.particle.record)
            destroyFn(current, p.particle.index, true, true);
        ReleaseBinding(p.binding);
    }
    probeParticles.clear();
    probeLive.store(0);
}

// Demo time can be frozen while paused, so probe particles expire by demo time
// and are additionally bounded by kProbeMaxLive and destroyed on pause/reset.
void ExpireProbeOwned(double time) {
    if(probeParticles.empty()) return;
    void * current = managerFn ? managerFn() : nullptr;
    for(auto it = probeParticles.begin(); it != probeParticles.end();) {
        if(time >= it->end || current != it->manager) {
            if(destroyFn && current == it->manager && FindRecord(current, it->particle.index) == it->particle.record)
                destroyFn(current, it->particle.index, true, true);
            ReleaseBinding(it->binding);
            const unsigned value = probeLive.load();
            if(value) probeLive.store(value - 1);
            it = probeParticles.erase(it);
        } else ++it;
    }
}

void DropProbePending(int stage) {
    if(!probePending) return;
    probePending = false;
    probeRemaining = 0;
    probeDropped.fetch_add(1);
    probeStage.store(stage);
}

bool SpawnProbePulse(double time, unsigned pulse) {
    // Same validated native particle interfaces as the owned bolt: manager
    // lookup, resource precache plus retained binding, create with the same
    // attachment argument, record identity check, then CP0/CP1 update.
    if(!managerFn || !createFn || !updateFn || !destroyFn) { probeStage.store(MirvWeatherParticleStage_NativeInterface); return false; }
    if(!g_pCResourceSystem) { probeStage.store(MirvWeatherParticleStage_ResourceSystem); return false; }
    if(!resourcePinLayoutReady) { probeStage.store(MirvWeatherParticleStage_Layout); return false; }
    void * manager = managerFn();
    if(!manager) { probeStage.store(MirvWeatherParticleStage_Manager); return false; }
    if(probeParticles.size() >= kProbeMaxLive) DestroyProbeOwned();
    probeFired.fetch_add(1);
    void ** binding = reinterpret_cast<void **>(g_pCResourceSystem->PreCache(probeName));
    if(!binding || !*binding) {
        probeDefinitionFails.fetch_add(1);
        probeStage.store(MirvWeatherParticleStage_Definition);
        return false;
    }
    RetainBinding(binding);
    int index = -1;
    createFn(manager, &index, probeName, 8, 0, 0, 0, 0);
    void * record = FindRecord(manager, index);
    if(index < 0 || !record) {
        ReleaseBinding(binding);
        probeCreateFails.fetch_add(1);
        probeStage.store(index < 0 ? MirvWeatherParticleStage_Create : MirvWeatherParticleStage_Record);
        return false;
    }
    const ProbePulse & placement = probePulseTable[pulse < kProbePulses ? pulse : kProbePulses - 1];
    const double yaw = g_CurrentGameCamera.angles[1] * 3.141592653589793 / 180;
    const float dirX = static_cast<float>(std::cos(yaw)), dirY = static_cast<float>(std::sin(yaw));
    const float originX = static_cast<float>(g_CurrentGameCamera.origin[0]);
    const float originY = static_cast<float>(g_CurrentGameCamera.origin[1]);
    const float originZ = static_cast<float>(g_CurrentGameCamera.origin[2]);
    Vec3 start { originX + dirX * placement.forward, originY + dirY * placement.forward, originZ + placement.height };
    Vec3 end { start.x, start.y, start.z + placement.length };
    updateFn(manager, index, 0, &start, 0.0f);
    updateFn(manager, index, 1, &end, 0.0f);
    probeParticles.push_back({{index, record}, manager, binding, time + kProbeLifetime});
    probeCreated.fetch_add(1);
    probeLive.fetch_add(1);
    probeStage.store(MirvWeatherParticleStage_None);
    return true;
}

bool ReadContact(CEntityInstance * entity, uint32_t & group, bool & enabled) {
    if(!entity || !contactSchemaReady) return false;
    auto * bytes = reinterpret_cast<unsigned char *>(entity);
    auto * identity = *reinterpret_cast<unsigned char **>(bytes + identityOffset);
    if(!identity) return false;
    group = *reinterpret_cast<uint32_t *>(identity + worldGroupOffset);
    enabled = *reinterpret_cast<bool *>(bytes + rainContactOffset);
    return true;
}

bool ResolveContact(uint32_t group, void *& scene, void *& world) {
    if(!worldFn || !contactSceneAddress || !contactWorldAddress) return false;
    scene = *contactSceneAddress;
    if(!scene || !*contactWorldAddress) return false;
    world = worldFn(*contactWorldAddress, group);
    return world != nullptr;
}

void PublishContact(void * scene, void * world, bool enabled) {
    // CMapInfo uses this same scene-world setter when its authored map data is
    // loaded. Do not call its entire initializer or add another rainfall source.
    auto ** vtable = *reinterpret_cast<void ***>(scene);
    auto setter = reinterpret_cast<RainContactFn>(vtable[0x1b8 / sizeof(void *)]);
    setter(scene, world, enabled);
}

void RestoreContact() {
    if(!g_pEntityList || !*g_pEntityList || !g_GetEntityFromIndex) {
        // Level teardown owns the destroyed scene worlds.
        contactStates.clear();
        return;
    }
    for(auto & state : contactStates) {
        void * scene = nullptr, * world = nullptr;
        if(!ResolveContact(state.worldGroup, scene, world) || scene != state.scene || world != state.world) continue;
        auto * entity = GetEntityFromIndex(state.handle.GetEntryIndex());
        if(entity && entity->GetHandle() == state.handle) {
            uint32_t group = 0;
            bool enabled = false;
            if(ReadContact(entity, group, enabled) && group == state.worldGroup) state.original = enabled;
        }
        PublishContact(scene, world, state.original);
    }
    contactStates.clear();
}

bool ReadEnvironment(CEntityInstance * entity, std::array<float, 5> & values) {
    if(!entity || !environmentSchemaReady) return false;
    for(size_t i = 0; i < values.size(); ++i) {
        values[i] = *reinterpret_cast<float *>(reinterpret_cast<unsigned char *>(entity) + environmentOffsets[i]);
        if(!std::isfinite(values[i])) return false;
    }
    return true;
}

void PublishEnvironment(void * scene, void * world, const std::array<float, 5> & values) {
    // Same five-float publication used by native CMapInfo initialization.
    auto ** table = *reinterpret_cast<void ***>(scene);
    auto setter = reinterpret_cast<RainEnvironmentFn>(table[0x1c8 / sizeof(void *)]);
    setter(scene, world, values[0], values[1], values[2], values[3], values[4]);
}

void RestoreEnvironment() {
    if(g_pEntityList && *g_pEntityList && g_GetEntityFromIndex) {
        for(auto & state : environmentStates) {
            auto * entity = GetEntityFromIndex(state.handle.GetEntryIndex());
            if(!entity || entity->GetHandle() != state.handle) continue;
            uint32_t group = 0;
            bool enabled = false;
            void * scene = nullptr, * world = nullptr;
            if(!ReadContact(entity, group, enabled) || group != state.worldGroup
                || !ResolveContact(group, scene, world) || scene != state.scene || world != state.world) continue;
            // We publish to the scene, not to entity fields. Native values remain
            // the current source of truth even if the map changed them while on.
            if(ReadEnvironment(entity, state.original)) PublishEnvironment(scene, world, state.original);
        }
    }
    environmentStates.clear();
}

void ApplyEnvironment() {
    if(!environmentSignatureReady || !environmentSchemaReady || !contactSchemaReady
        || !worldFn || !g_pEntityList || !*g_pEntityList || !g_GetEntityFromIndex) {
        if(!environmentWarning) {
            environmentWarning = true;
            advancedfx::Warning("[mirv_weather] Native environment interface/schema unavailable; environment left unchanged.\n");
        }
        return;
    }
    for(const auto & handle : mapInfoHandles) {
        auto * entity = GetEntityFromIndex(handle.GetEntryIndex());
        if(!entity || entity->GetHandle() != handle) continue;
        uint32_t group = 0;
        bool enabled = false;
        void * scene = nullptr, * world = nullptr;
        std::array<float, 5> original {};
        if(!ReadContact(entity, group, enabled) || !ReadEnvironment(entity, original)
            || !ResolveContact(group, scene, world)) continue;
        auto it = environmentStates.begin();
        while(it != environmentStates.end() && it->handle != handle) ++it;
        if(it == environmentStates.end()) {
            if(environmentStates.size() >= 32) continue;
            environmentStates.push_back({handle, group, scene, world, original});
        } else *it = {handle, group, scene, world, original};
        PublishEnvironment(scene, world, weatherEnvironment);
    }
}

void DiscoverWeatherEntities() {
    if(!g_pEntityList || !*g_pEntityList || !g_GetEntityFromIndex) return;
    const ULONGLONG now = GetTickCount64();
    if(lastEntityScan && now - lastEntityScan < 1000) return;
    lastEntityScan = now;
    mapInfoHandles.clear();
    postVolumeHandles.clear();
    // The native getter accepts 0..0x7ffe, including client-only map objects.
    // The legacy script helper's hardcoded 2048 is not an entity namespace bound.
    for(int i = 0; i < 0x7fff; ++i) {
        auto * entity = GetEntityFromIndex(i);
        if(!entity) continue;
        auto ** vtable = *reinterpret_cast<void ***>(entity);
        if(vtable != mapInfoVtable && vtable != postVolumeVtable) continue;
        auto handle = entity->GetHandle();
        if(!handle.IsValid()) continue;
        if(vtable == mapInfoVtable) mapInfoHandles.push_back(handle);
        if(vtable == postVolumeVtable) postVolumeHandles.push_back(handle);
    }
}

void ApplyContact() {
    if(!contactSchemaReady || !worldFn || !g_pEntityList || !*g_pEntityList
        || !mapInfoVtable || !g_GetEntityFromIndex) {
        if(!contactWarning) {
            contactWarning = true;
            advancedfx::Warning("[mirv_weather] Native rain contact interface/schema unavailable; contact left unchanged.\n");
        }
        return;
    }
    for(const auto & cachedHandle : mapInfoHandles) {
        auto * entity = GetEntityFromIndex(cachedHandle.GetEntryIndex());
        if(!entity || entity->GetHandle() != cachedHandle) continue;
        auto handle = entity->GetHandle();
        uint32_t group = 0;
        bool original = false;
        void * scene = nullptr, * world = nullptr;
        if(!handle.IsValid() || !ReadContact(entity, group, original) || !ResolveContact(group, scene, world)) continue;
        auto it = contactStates.begin();
        while(it != contactStates.end() && it->handle != handle) ++it;
        if(it == contactStates.end()) {
            if(contactStates.size() >= 32) continue;
            contactStates.push_back({handle, group, scene, world, original});
        } else *it = {handle, group, scene, world, original};
        // The reference Dust2 profile changes only raintracetoskyenabled.
        // Preserve its existing rain strength, wetness and drying parameters.
        PublishContact(scene, world, true);
    }
}

bool ReadConfig() {
    if(loadAttempted) return configLoaded;
    if(!loadedProfile) return false;
    loadAttempted = true;
    const auto root = std::filesystem::path(GetHlaeFolderW()) / L"resources/AfxHookSource2/cs2/mirv_weather";
    std::ifstream f(root / loadedProfile->file);
    std::string line;
    std::string magic, map, extra;
    size_t rainCount = 0, materialCount = 0;
    if(std::getline(f, line)) {
        std::istringstream header(line);
        header >> magic >> map >> rainCount >> materialCount;
        header >> extra;
    }
    if(magic != "MIRV_MAP_WEATHER_2" || map != loadedProfile->map || !extra.empty()
        || rainCount != loadedProfile->rainCount || materialCount != loadedProfile->materialCount) {
        advancedfx::Warning("[mirv_weather] %s resource profile missing or unsupported. Install the seven-map resources, then use mirv_weather reload.\n", loadedProfile->map);
        return false;
    }
    bool hasEnvironment = false, parsed = true;
    while(std::getline(f, line)) {
        if(line.empty() || line[0] == '#') continue;
        std::istringstream row(line);
        std::string type;
        row >> type;
        if(type == "environment") {
            if(hasEnvironment) { parsed = false; break; }
            bool valid = true;
            for(float & value : weatherEnvironment)
                if(!(row >> value) || !std::isfinite(value) || value < 0 || value > 1) valid = false;
            if(!valid) { parsed = false; break; }
            hasEnvironment = true;
        } else if(type == "rain") {
            Vec3 p {};
            if(!(row >> p.x >> p.y >> p.z) || !std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z)
                || fabsf(p.x) > 32768 || fabsf(p.y) > 32768 || fabsf(p.z) > 32768 || positions.size() >= loadedProfile->rainCount) { parsed = false; break; }
            positions.push_back(p);
        } else if(type == "material") {
            MaterialEntry e;
            if(!(row >> e.original >> e.wet) || e.original.find("materials/") != 0
                || e.wet.find("materials/mirv_weather/") != 0 || e.wet.find("..") != std::string::npos
                || e.original.find("..") != std::string::npos || e.original.size() > 256 || e.wet.size() > 256
                || e.original.size() < 6 || e.original.compare(e.original.size()-5, 5, ".vmat") != 0
                || e.wet.size() < 6 || e.wet.compare(e.wet.size()-5, 5, ".vmat") != 0
                || materialEntries.size() >= loadedProfile->materialCount) { parsed = false; break; }
            e.original = Normalize(e.original);
            materialEntries.push_back(e);
        } else { parsed = false; break; }
        if(row >> extra) { parsed = false; break; }
    }
    if(!parsed || !f.eof() || !hasEnvironment || positions.size() != rainCount || materialEntries.size() != materialCount) {
        positions.clear(); materialEntries.clear();
        advancedfx::Warning("[mirv_weather] Invalid %s resource profile; effects left off.\n", loadedProfile->map);
        return false;
    }
    configLoaded = true;
    return true;
}

void LoadMaterials() {
    if(materialEntries.empty()) return; // native ground / rain-only map profile
    if(groundReady || groundLoadAttempted || !g_pCResourceSystem) return;
    groundLoadAttempted = true;
    if(!resourcePinLayoutReady) {
        advancedfx::Warning("[mirv_weather] Resource reference layout unavailable; ground left unchanged.\n");
        return;
    }
    std::unordered_map<std::string, CMaterial2 *> loaded;
    std::vector<CMaterial2 **> retained;
    for(const auto & e : materialEntries) {
        g_pCResourceSystem->PreCache(e.wet.c_str());
        auto ** material = FindRenderMaterial(e.wet.c_str());
        if(material) {
            InterlockedIncrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(material) + 0x20));
            retained.push_back(material);
        }
        if(!material || !*material || !MaterialRenderCallbacksReady(*material)) {
            advancedfx::Warning("[mirv_weather] Wet material has no callable render interface: %s; ground left unchanged.\n", e.wet.c_str());
            for(auto ** binding : retained) InterlockedDecrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(binding) + 0x20));
            return;
        }
        const char * name = material && *material ? (*material)->GetName() : nullptr;
        const std::string resolved = name ? Normalize(name) : std::string();
        // Renaming the loose compiled file does not rename its m_materialName.
        // Accept only the requested name or this manifest entry's authored name;
        // keep rejecting default/error materials and unrelated resource aliases.
        if(!name || (resolved != Normalize(e.wet) && resolved != e.original)) {
            advancedfx::Warning("[mirv_weather] Wet material could not be loaded: %s (resolved=%s).\n", e.wet.c_str(), name ? name : "<null>");
            for(auto ** binding : retained) InterlockedDecrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(binding) + 0x20));
            return;
        }
        // Current ResourceBinding reference count is +0x20 (verified against
        // the native zero-reference deletion check); hold our loaded resources.
        loaded[e.original] = *material;
    }
    std::unique_lock<std::shared_mutex> lock(materialMutex);
    wetMaterials.swap(loaded);
    retainedWetBindings.swap(retained);
    groundReady = true;
}

void StartRain() {
    // Each guard records the early-return reason so a failed rain start can be
    // told apart from a missing interface, layout or definition.
    if(!managerFn || !createFn || !updateFn || !destroyFn) { rainCounters.stage.store(MirvWeatherParticleStage_NativeInterface); return; }
    if(!g_pCResourceSystem) { rainCounters.stage.store(MirvWeatherParticleStage_ResourceSystem); return; }
    if(!resourcePinLayoutReady) { rainCounters.stage.store(MirvWeatherParticleStage_Layout); return; }
    if(rainAttempted) return;
    rainAttempted = true;
    rainCounters.tries.fetch_add(1);
    // The generic resource precache wrapper accepts particle definitions too.
    auto ** resource = g_pCResourceSystem->PreCache(rainName);
    if(!resource || !*resource) {
        rainCounters.definitionFails.fetch_add(1);
        rainCounters.stage.store(MirvWeatherParticleStage_Definition);
        advancedfx::Warning("[mirv_weather] Rain particle resource could not be loaded.\n");
        return;
    }
    rainManager = managerFn();
    if(!rainManager) { rainAttempted = false; rainCounters.stage.store(MirvWeatherParticleStage_Manager); return; }
    rainResource = reinterpret_cast<void **>(resource);
    RetainBinding(rainResource);
    for(const auto & position : positions) {
        int index = -1;
        // World-origin attachment, as used by the native spectator trail.
        createFn(rainManager, &index, rainName, 8, 0, 0, 0, 0);
        if(index < 0) { rainCounters.createFails.fetch_add(1); rainCounters.stage.store(MirvWeatherParticleStage_Create); continue; }
        auto * record = FindRecord(rainManager, index);
        if(!record) { rainCounters.createFails.fetch_add(1); rainCounters.stage.store(MirvWeatherParticleStage_Record); continue; }
        updateFn(rainManager, index, 0, &position, 0.0f);
        rainParticles.push_back({index, record});
        rainCounters.created.fetch_add(1);
    }
    rainCounters.live.store(static_cast<unsigned>(rainParticles.size()));
    if(rainParticles.size() == positions.size()) rainCounters.stage.store(MirvWeatherParticleStage_None);
    advancedfx::Message("[mirv_weather] Rain hosts created: %zu/%zu.\n", rainParticles.size(), positions.size());
}

void ApplyPost() {
    if((postSettingsOffset != 0x1190 || !postLifetimeLayoutReady || !resourcePinLayoutReady) && !postSchemaWarning) {
        postSchemaWarning = true;
        advancedfx::Warning("[mirv_weather] Postprocessing ownership layout unavailable; postprocessing left unchanged.\n");
    }
    if(postSettingsOffset != 0x1190 || !postLifetimeLayoutReady || !resourcePinLayoutReady || !g_pCResourceSystem || !g_pEntityList || !*g_pEntityList
        || !postVolumeVtable || !g_GetEntityFromIndex) return;
    if(!postReady) {
        if(postLoadAttempted) return;
        postLoadAttempted = true;
        postResource = reinterpret_cast<void **>(g_pCResourceSystem->PreCache(
            "lighting/postprocessing/de_train_prefab/de_train_postprocess.vpost"));
        postReady = postResource && *postResource;
        if(!postReady) { postResource = nullptr; advancedfx::Warning("[mirv_weather] Train postprocessing resource unavailable.\n"); return; }
        RetainBinding(postResource); // controller ownership, separate from each entity field
    }
    for(const auto & cachedHandle : postVolumeHandles) {
        auto * entity = GetEntityFromIndex(cachedHandle.GetEntryIndex());
        if(!entity || entity->GetHandle() != cachedHandle) continue;
        auto handle = entity->GetHandle();
        if(!handle.IsValid()) continue;
        auto *** field = reinterpret_cast<void ***>(reinterpret_cast<unsigned char *>(entity) + postSettingsOffset);
        if(*field == postResource) continue;
        auto it = postBackups.begin();
        while(it != postBackups.end() && it->handle != handle) ++it;
        RetainBinding(*field); // keep the original alive until restoration, including seeks
        if(it == postBackups.end()) postBackups.push_back({handle, *field});
        else {
            ReleaseBinding(it->original);
            it->original = *field; // honor native changes made while enabled
        }
        ReplacePostBinding(field, postResource);
    }
}

void PrintStatus() {
    const auto * profile = GetDemoProfile();
    advancedfx::Message("[mirv_weather] requested=%d map=%s supportedDemo=%d pack=%d; rain=%d hosts=%zu/%zu native=%d; ground=%d materials=%zu/%zu; postprocess=%d volumes=%zu schema=%d.\n",
        requested, profile ? profile->map : "unsupported", profile != nullptr, configLoaded,
        wantRain, rainParticles.size(), profile ? profile->rainCount : 0, destroyFn && managerFn && createFn && updateFn,
        groundActive.load(), wetMaterials.size(), profile ? profile->materialCount : 0, wantPost, postBackups.size(), postSettingsOffset > 0);
    advancedfx::Message("[mirv_weather] contact requested=%d active=%d worlds=%zu interface=%d schema=%d.\n",
        wantContact && MirvPovDebug_IsFeatureEnabled("weather_contact"), !contactStates.empty(), contactStates.size(),
        worldFn != nullptr, contactSchemaReady);
    advancedfx::Message("[mirv_weather] map objects: mapInfo=%zu postVolumes=%zu RTTI=%d/%d; ground requested=%d debug=%d ready=%d.\n",
        mapInfoHandles.size(), postVolumeHandles.size(), mapInfoVtable != nullptr, postVolumeVtable != nullptr,
        wantGround, MirvPovDebug_IsFeatureEnabled("weather_ground"), groundReady);
    advancedfx::Message("[mirv_weather] environment requested=%d worlds=%zu interface=%d schema=%d; ground profile=%s.\n",
        MirvPovDebug_IsFeatureEnabled("weather_environment"), environmentStates.size(), environmentSignatureReady,
        environmentSchemaReady, profile && profile->materialCount ? "wet-materials" : "native-ground");
    // Particle submission counters. They show how far each owned resource got;
    // a created/live count is not proof that the effect is visible. The
    // authored bolt and the optional native cloud are reported separately.
    const MirvWeatherParticleStatus particles=MirvWeather_ParticleStatus();
    advancedfx::Message("[mirv_weather] lightning spawn: tries=%u stage=%s; bolt tries=%u def=%u fail=%u created=%u live=%u stage=%s; cloud tries=%u def=%u fail=%u created=%u live=%u stage=%s.\n",
        particles.lightningTries,MirvWeather_ParticleStageName(particles.lightningStage),
        particles.lightningBolt.tries,particles.lightningBolt.definitionFails,particles.lightningBolt.createFails,
        particles.lightningBolt.created,particles.lightningBolt.live,MirvWeather_ParticleStageName(particles.lightningBolt.stage),
        particles.lightningCloud.tries,particles.lightningCloud.definitionFails,particles.lightningCloud.createFails,
        particles.lightningCloud.created,particles.lightningCloud.live,MirvWeather_ParticleStageName(particles.lightningCloud.stage));
    advancedfx::Message("[mirv_weather] rain spawn: tries=%u def=%u fail=%u created=%u live=%u stage=%s; native=%d layout=%d resources=%d manager=%d.\n",
        particles.rain.tries,particles.rain.definitionFails,particles.rain.createFails,particles.rain.created,particles.rain.live,
        MirvWeather_ParticleStageName(particles.rain.stage),
        destroyFn && managerFn && createFn && updateFn,resourcePinLayoutReady,g_pCResourceSystem!=nullptr,managerFn!=nullptr);
    // Manual control-probe counters. They are deliberately separate from the
    // authored bolt/cloud and from the demo/kill/manual event counters: the
    // probe spawns only the native control definition and creates no flash,
    // kill or thunder event. A created/live count still only proves submission.
    const MirvWeatherProbeStatus probe=MirvWeather_ProbeStatus();
    advancedfx::Message("[mirv_weather] lightning probe: queued=%u dropped=%u pending=%d left=%d fired=%u; def=%u fail=%u created=%u live=%u stage=%s; control=%s.\n",
        probe.queued,probe.dropped,probe.pending?1:0,probe.remaining,probe.fired,
        probe.definitionFails,probe.createFails,probe.created,probe.live,MirvWeather_ParticleStageName(probe.stage),probeName);
    MirvWeatherStorm_Status();
}

size_t UniqueAddress(HMODULE dll, const char * pattern) {
    Afx::BinUtils::ImageSectionsReader sections(dll);
    auto range = sections.GetMemRange();
    auto found = FindPatternString(range, pattern);
    if(found.IsEmpty()) return 0;
    Afx::BinUtils::MemRange remainder(found.Start + 1, range.End);
    if(!FindPatternString(remainder, pattern).IsEmpty()) return 0;
    return found.Start;
}
} // namespace

void MirvWeather_Initialize(HMODULE clientDll) {
    MirvWeatherStorm_Initialize(clientDll);
    if(HMODULE resources = GetModuleHandleA("resourcesystem.dll"))
        resourcePinLayoutReady = 0 != UniqueAddress(resources, "8B 43 20 85 C0 0F 84 ?? ?? ?? ?? 48 0F BE 43 1C 48 83 C5 D0 3C FF");
    postLifetimeLayoutReady = 0 != UniqueAddress(clientDll, "48 8B 91 90 11 00 00 48 85 D2 74 ?? 48 83 3D ?? ?? ?? ?? 00 74 ?? F0 FF 4A 20");
    environmentSignatureReady = 0 != UniqueAddress(clientDll, "F3 0F 10 B6 2C 06 00 00 F3 0F 10 BE 28 06 00 00 48 8B 08 8B 52 38 F3 44 0F 10 86 24 06 00 00 F3 44 0F 10 8E 20 06 00 00");
    // These non-networked map classes inherit a base network-class descriptor.
    // Match their actual dynamic type instead of GetClientClassName().
    mapInfoVtable = reinterpret_cast<void **>(Afx::BinUtils::FindClassVtable(clientDll, ".?AVCMapInfo@@", 0, 0));
    postVolumeVtable = reinterpret_cast<void **>(Afx::BinUtils::FindClassVtable(clientDll, ".?AVC_PostProcessingVolume@@", 0, 0));
    managerFn = reinterpret_cast<ManagerFn>(UniqueAddress(clientDll, "48 8B 05 ?? ?? ?? ?? C3 CC CC CC CC CC CC CC CC 48 89 5C 24 10 57"));
    createFn = reinterpret_cast<CreateFn>(UniqueAddress(clientDll, "4C 8B DC 53 48 81 EC ?? ?? ?? ?? F2 0F 10 05"));
    updateFn = reinterpret_cast<UpdateFn>(UniqueAddress(clientDll, "48 89 5C 24 ?? 48 89 74 24 ?? 57 48 83 EC ?? F3 0F 10 1D ?? ?? ?? ?? 41 8B F8 8B DA 4C 8D 05"));
    destroyFn = reinterpret_cast<DestroyFn>(UniqueAddress(clientDll, "83 FA FF 0F 84 ?? ?? ?? ?? 41 54 41 56 41 57 48 83 EC 40 48 89 5C 24 60 45 0F B6 E1 33 DB 48 89 74 24 38 48 8D B1 98 00 00 00 45 0F B6 F0"));
    size_t callSite = UniqueAddress(clientDll, "48 8B 05 ?? ?? ?? ?? 48 8B 56 10 0F B6 9E 19 06 00 00 48 8B 08 8B 52 38 48 8B B9 B8 01 00 00 48 8B 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 44 0F B6 C3 48 8B D0 FF D7");
    if(callSite) {
        contactSceneAddress = reinterpret_cast<void **>(callSite + 7 + *reinterpret_cast<int32_t *>(callSite + 3));
        contactWorldAddress = reinterpret_cast<void **>(callSite + 38 + *reinterpret_cast<int32_t *>(callSite + 34));
        worldFn = reinterpret_cast<WorldFn>(callSite + 43 + *reinterpret_cast<int32_t *>(callSite + 39));
    }
}

void MirvWeather_ResolveSchemaOffsets() {
    MirvWeatherStorm_ResolveSchema();
    // HookSchemaSystem clears the temporary schema table after initialization.
    // Resolve optional weather fields while that table is still populated.
    getOffset(&postSettingsOffset, "client.dll", "C_PostProcessingVolume", "m_hPostSettings");
    getOffset(&identityOffset, "client.dll", "CEntityInstance", "m_pEntity");
    getOffset(&worldGroupOffset, "client.dll", "CEntityIdentity", "m_worldGroupId");
    getOffset(&rainContactOffset, "client.dll", "CMapInfo", "m_bRainTraceToSkyEnabled");
    // The verified native signature embeds this layout; do not guess if it changes.
    contactSchemaReady = identityOffset == 0x10 && worldGroupOffset == 0x38 && rainContactOffset == 0x619;
    const char * names[] = { "m_flEnvRainStrength", "m_flEnvPuddleRippleStrength", "m_flEnvPuddleRippleDirection", "m_flEnvWetnessCoverage", "m_flEnvWetnessDryingAmount" };
    environmentSchemaReady = true;
    for(size_t i = 0; i < environmentOffsets.size(); ++i) {
        getOffset(&environmentOffsets[i], "client.dll", "CMapInfo", names[i]);
        if(environmentOffsets[i] != 0x61c + static_cast<ptrdiff_t>(i * 4)) environmentSchemaReady = false;
    }
}

void MirvWeather_Reset() {
    MirvWeatherStorm_Reset();
    ClearLightning(true);
    groundActive.store(false);
    StopRain();
    RestorePost();
    RestoreEnvironment();
    RestoreContact();
    mapInfoHandles.clear();
    postVolumeHandles.clear();
    lastEntityScan = 0;
    std::unique_lock<std::shared_mutex> lock(materialMutex);
    wetMaterials.clear();
    for(auto ** binding : retainedWetBindings)
        InterlockedDecrement(reinterpret_cast<LONG *>(reinterpret_cast<unsigned char *>(binding) + 0x20));
    retainedWetBindings.clear();
    groundReady = false;
    groundLoadAttempted = postLoadAttempted = false;
    postReady = false;
    ReleaseBinding(postResource);
    postResource = nullptr;
    previousTick = -1;
    loadedProfile = nullptr;
    configLoaded = loadAttempted = false;
    lightningWarning = false;
    // A resource lookup that failed transiently (for example while the map's
    // resource system was still warming up) must be retryable; without this a
    // single failure would disable storm audio until process restart.
    audioPrecacheFailed = false;
    positions.clear();
    materialEntries.clear();
}

void MirvWeather_Frame(bool fromRenderFrame) {
    const MapProfile * profile = requested ? GetDemoProfile() : nullptr;
    // No supported active demo means no weather layer: drop a queued control
    // probe even when the map-owned state was never loaded (for example after
    // the weather master switch was turned off).
    if(!profile) { if(loadedProfile) MirvWeather_Reset(); else MirvWeather_ClearLightningProbe(); return; }
    // The master preference survives map changes, all map-owned resources do not.
    if(profile != loadedProfile) {
        MirvWeather_Reset();
        loadedProfile = profile;
    }
    if(!ReadConfig()) return;
    const int tick = g_pEngineToClient->GetDemoFile()->GetDemoTick();
    // Avoid retaining particle state across a rewind or large demo jump.
    if(previousTick >= 0 && (tick < previousTick || tick - previousTick > 128)) { MirvWeatherStorm_Reset(); ClearLightning(true); StopRain(); RestorePost(); RestoreEnvironment(); RestoreContact(); lastEntityScan = 0; }
    previousTick = tick;
    DiscoverWeatherEntities();
    if(!rainParticles.empty() && (managerFn() != rainManager
        || FindRecord(rainManager, rainParticles.front().index) != rainParticles.front().record
        || FindRecord(rainManager, rainParticles.back().index) != rainParticles.back().record)) StopRain();
    if(wantRain && MirvPovDebug_IsFeatureEnabled("weather_rain")) StartRain(); else StopRain();
    if(wantGround && MirvPovDebug_IsFeatureEnabled("weather_ground")) LoadMaterials();
    groundActive.store(wantGround && groundReady && MirvPovDebug_IsFeatureEnabled("weather_ground"));
    if(wantPost && MirvPovDebug_IsFeatureEnabled("weather_postprocess")) ApplyPost(); else RestorePost();
    if(MirvPovDebug_IsFeatureEnabled("weather_environment")) ApplyEnvironment(); else RestoreEnvironment();
    if(wantContact && MirvPovDebug_IsFeatureEnabled("weather_contact")) ApplyContact(); else RestoreContact();
    ClearLightning(false);
    MirvWeatherStorm_Frame(true, fromRenderFrame);
}

bool MirvWeather_SpawnLightning(const float start[3], const float end[3]) {
    // Every early return records the stage, so the status line can say why a
    // manual or scheduled event produced no owned particle.
    lightningTries.fetch_add(1);
    if(!requested) { lightningStage.store(MirvWeatherParticleStage_Requested); return false; }
    if(!loadedProfile) { lightningStage.store(MirvWeatherParticleStage_Profile); return false; }
    if(!configLoaded) { lightningStage.store(MirvWeatherParticleStage_Config); return false; }
    if(!resourcePinLayoutReady) { lightningStage.store(MirvWeatherParticleStage_Layout); return false; }
    if(!managerFn || !createFn || !updateFn || !destroyFn) { lightningStage.store(MirvWeatherParticleStage_NativeInterface); return false; }
    if(!g_pCResourceSystem) { lightningStage.store(MirvWeatherParticleStage_ResourceSystem); return false; }
    if(transientParticles.size()>=8) ClearLightning(true);
    void * manager=managerFn(); if(!manager) { lightningStage.store(MirvWeatherParticleStage_Manager); return false; }
    double time=0; if(!g_MirvTime.GetCurrentDemoTime(time)) { lightningStage.store(MirvWeatherParticleStage_Time); return false; }
    bool created=false;
    int lastFail=MirvWeatherParticleStage_None;
    for(unsigned resource=0;resource<kLightningResources;++resource) {
        const char * name=lightningNames[resource];
        ParticleCounters & counters=lightningRes[resource];
        counters.tries.fetch_add(1);
        void ** binding=reinterpret_cast<void **>(g_pCResourceSystem->PreCache(name));
        if(!binding || !*binding) {
            counters.definitionFails.fetch_add(1);
            counters.stage.store(MirvWeatherParticleStage_Definition);
            lastFail=MirvWeatherParticleStage_Definition;
            continue;
        }
        RetainBinding(binding);
        int index=-1; createFn(manager,&index,name,8,0,0,0,0);
        void * record=FindRecord(manager,index);
        if(index<0 || !record) {
            ReleaseBinding(binding);
            counters.createFails.fetch_add(1);
            const int stage=index<0?MirvWeatherParticleStage_Create:MirvWeatherParticleStage_Record;
            counters.stage.store(stage);
            lastFail=stage;
            continue;
        }
        Vec3 a {start[0],start[1],start[2]}, b {end[0],end[1],end[2]};
        updateFn(manager,index,0,&a,0); updateFn(manager,index,1,&b,0);
        transientParticles.push_back({{index,record},manager,binding,time+lightningLifetime[resource],static_cast<int>(resource)});
        counters.created.fetch_add(1);
        counters.live.fetch_add(1);
        created=true;
    }
    lightningStage.store(created?MirvWeatherParticleStage_None:lastFail);
    if(!created && !lightningWarning) {
        lightningWarning=true;
        advancedfx::Warning("[mirv_weather] Owned storm lightning particles could not be created; particle lightning left off.\n");
    }
    return created;
}

bool MirvWeather_RetainAudioData() {
    // A failed definition lookup is not retried every frame: the weather
    // resource pack is static, and per-frame retries would both spam and
    // repeatedly call the native precache path for the same missing resource.
    // It is cleared by MirvWeather_Reset instead, so a reload, map change or
    // master off/on can recover from a transient resource failure.
    if(audioPrecacheFailed) return false;
    if(!resourcePinLayoutReady || !g_pCResourceSystem) return false;
    if(!audioBindings.empty()) return true;
    for(const char * name:{"soundevents/ambience/game_sounds_train.vsndevts","soundevents/ambience/game_sounds_amb_common.vsndevts"}) {
        auto ** binding=reinterpret_cast<void **>(g_pCResourceSystem->PreCache(name));
        if(!binding || !*binding) {
            MirvWeather_ReleaseAudioData();
            audioPrecacheFailed=true;
            advancedfx::Warning("[mirv_weather] Native rain/thunder sound definitions unavailable; storm audio left off.\n");
            return false;
        }
        RetainBinding(binding);audioBindings.push_back(binding);
    }
    return true;
}
void MirvWeather_ReleaseAudioData() {
    for(auto ** binding:audioBindings)ReleaseBinding(binding);
    audioBindings.clear();
}

void MirvWeather_ClearLightning() { ClearLightning(true); }

void MirvWeather_QueueLightningProbe() {
    // Transient manual request. The three pulses start kProbeDelay demo seconds
    // later and are spaced kProbeSpacing apart, so the console can be closed
    // before the short control effect appears. The request is not part of the
    // demo interval or kill schedule and creates no flash, kill or thunder.
    double time = 0;
    const bool haveTime = g_MirvTime.GetCurrentDemoTime(time) && std::isfinite(time);
    probePending = true;
    probeRemaining = static_cast<int>(kProbePulses);
    probeFireAt = haveTime ? time + kProbeDelay : -1;
    probeQueued.fetch_add(1);
    probeStage.store(MirvWeatherParticleStage_Queued);
    advancedfx::Message("[mirv_weather] Control probe queued: %u pulses, first in %.2f demo seconds, spaced %.2f s. The demo must stay running: pausing, seeking, changing map or switching the storm/weather layer off drops the request.\n",
        kProbePulses,kProbeDelay,kProbeSpacing);
}

void MirvWeather_ClearLightningProbe() {
    DestroyProbeOwned();
    DropProbePending(MirvWeatherParticleStage_Dropped);
}

void MirvWeather_LightningProbeFrame(bool fromRenderFrame, bool paused, double time) {
    if(!std::isfinite(time)) return;
    if(paused) {
        // Pause freezes demo time, so a delayed pulse can never expire on its
        // own. Drop the pending sequence together with any owned probe
        // particle instead of replaying it after unpause.
        DropProbePending(MirvWeatherParticleStage_Paused);
        DestroyProbeOwned();
        return;
    }
    ExpireProbeOwned(time);
    if(!probePending) return;
    if(probeFireAt < 0) probeFireAt = time + kProbeDelay;
    // Only the normal render frame may fire a pulse, so the command-side frame
    // of the queuing command can never consume the delay.
    if(!fromRenderFrame || time < probeFireAt) return;
    while(probePending && probeRemaining > 0 && time >= probeFireAt) {
        const unsigned pulse = kProbePulses - static_cast<unsigned>(probeRemaining);
        SpawnProbePulse(time, pulse);
        --probeRemaining;
        probeFireAt += kProbeSpacing;
        if(probeRemaining == 0) probePending = false;
    }
}

MirvWeatherProbeStatus MirvWeather_ProbeStatus() {
    MirvWeatherProbeStatus status {};
    status.queued = probeQueued.load();
    status.dropped = probeDropped.load();
    status.fired = probeFired.load();
    status.definitionFails = probeDefinitionFails.load();
    status.createFails = probeCreateFails.load();
    status.created = probeCreated.load();
    status.live = probeLive.load();
    status.stage = probeStage.load();
    status.pending = probePending;
    status.remaining = probePending ? probeRemaining : 0;
    return status;
}

const char * MirvWeather_ParticleStageName(int stage) {
    switch(stage) {
    case MirvWeatherParticleStage_None: return "none";
    case MirvWeatherParticleStage_Requested: return "requested";
    case MirvWeatherParticleStage_Profile: return "profile";
    case MirvWeatherParticleStage_Config: return "config";
    case MirvWeatherParticleStage_Layout: return "layout";
    case MirvWeatherParticleStage_NativeInterface: return "native-interface";
    case MirvWeatherParticleStage_ResourceSystem: return "resource-system";
    case MirvWeatherParticleStage_Manager: return "manager";
    case MirvWeatherParticleStage_Time: return "time";
    case MirvWeatherParticleStage_Definition: return "definition";
    case MirvWeatherParticleStage_Create: return "create";
    case MirvWeatherParticleStage_Record: return "record";
    case MirvWeatherParticleStage_Queued: return "queued";
    case MirvWeatherParticleStage_Paused: return "paused";
    case MirvWeatherParticleStage_Dropped: return "dropped";
    default: return "unknown";
    }
}

static MirvWeatherParticleResourceStatus ParticleResourceStatus(const ParticleCounters & counters) {
    MirvWeatherParticleResourceStatus status {};
    status.tries=counters.tries.load();
    status.definitionFails=counters.definitionFails.load();
    status.createFails=counters.createFails.load();
    status.created=counters.created.load();
    status.live=counters.live.load();
    status.stage=counters.stage.load();
    return status;
}

MirvWeatherParticleStatus MirvWeather_ParticleStatus() {
    MirvWeatherParticleStatus status {};
    status.lightningBolt=ParticleResourceStatus(lightningRes[0]);
    status.lightningCloud=ParticleResourceStatus(lightningRes[1]);
    status.lightningTries=lightningTries.load();
    status.lightningStage=lightningStage.load();
    status.rain=ParticleResourceStatus(rainCounters);
    return status;
}

int MirvWeather_AudioDefinitionCount() { return static_cast<int>(audioBindings.size()); }
int MirvWeather_AudioDefinitionTargets() { return 2; }
bool MirvWeather_AudioPrecacheFailed() { return audioPrecacheFailed; }

bool MirvWeather_HasGroundOverride() { return groundActive.load(); }

CMaterial2 * MirvWeather_Material(CMaterial2 * original) {
    if(!original || !groundActive.load()) return original;
    std::shared_lock<std::shared_mutex> lock(materialMutex);
    const char * name = original->GetName();
    if(!name) return original;
    auto it = wetMaterials.find(Normalize(name));
    return it == wetMaterials.end() ? original : it->second;
}

CON_COMMAND(mirv_weather, "Seven-map demo rain, native rain contact/environment, wet ground and postprocessing") {
    if(MirvWeatherStorm_Command(args)) {
        // Storm options are independent of the base rain/ground profile.
    } else if(args->ArgC() == 2 && (!strcmp(args->ArgV(1), "0") || !strcmp(args->ArgV(1), "1"))) {
        requested = args->ArgV(1)[0] == '1';
        if(!requested) MirvWeather_Reset();
    } else if(args->ArgC() == 3 && (!strcmp(args->ArgV(2), "0") || !strcmp(args->ArgV(2), "1"))) {
        bool * target = nullptr;
        if(!_stricmp(args->ArgV(1), "rain")) target = &wantRain;
        if(!_stricmp(args->ArgV(1), "ground")) target = &wantGround;
        if(!_stricmp(args->ArgV(1), "postprocess")) target = &wantPost;
        if(!_stricmp(args->ArgV(1), "contact")) target = &wantContact;
        if(target) *target = args->ArgV(2)[0] == '1';
    } else if(args->ArgC() == 2 && !_stricmp(args->ArgV(1), "reload")) {
        MirvWeather_Reset();
        configLoaded = loadAttempted = false;
        positions.clear(); materialEntries.clear();
    } else if(args->ArgC() != 2 || _stricmp(args->ArgV(1), "status")) {
        advancedfx::Message("mirv_weather 0|1; mirv_weather rain|ground|postprocess|contact 0|1; mirv_weather status|reload.\nStorm options: mirv_weather storm 0|1; mirv_weather lightning demo|kills|both|off; mirv_weather lightning test (diagnostic manual event); mirv_weather lightning probe (diagnostic native control-rope particle); mirv_weather interval 5..300; mirv_weather sun 0..1; mirv_weather exposure -3..1; mirv_weather rainsound 0..1; mirv_weather thunder 0..1.\nSeven-map offline demos: de_dust2, de_mirage, de_cache, de_inferno, de_ancient, de_nuke, de_anubis. Install the matching resources in HLAE. Native environment: mirv_pov_debug_feature weather_environment 0|1. Storm effects: mirv_pov_debug_feature weather_sun|weather_exposure|weather_grade|weather_lightning|weather_lightning_light|weather_rainsound|weather_thunder 0|1. Sky remains controlled by mirv_sky material.\n");
    }
    MirvWeather_Frame(false);
    PrintStatus();
}
